const translations = {
    es: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SIN ARCHIVO",
        kpi_reg: "REG",
        lbl_year: "AÑO",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Carga de Datos",
        upload_desc: "Sube tu archivo Excel (.xlsx) o CSV.",
        upload_drop: "ARRASTRAR O TOCAR PARA SUBIR",
        upload_mobile: "Compatible con móviles",
        btn_manual: "Ver Manual",
        btn_updates: "Actualizaciones",
        btn_memorias: "Memorias",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓN",
        config_desc: "Vincula las columnas de tu archivo.",
        col_id: "CONTADOR / ID",
        col_lat: "LATITUD (Y)",
        col_lon: "LONGITUD (X)",
        col_date: "FECHA (Obligatorio)",
        col_time: "HORA (Opcional)",
        col_street: "CALLE / DIRECCIÓN (Opcional)", 
        col_cat: "CATEGORÍA / TIPO",
        col_cat_desc: "Selecciona la columna que define el tipo de incidencia.",
        col_loc: "LOCALIDAD (Opcional)",
        col_loc_desc: "Escribe el nombre para forzar la zona. Déjalo vacío para GPS.",
        col_loc_placeholder: "Ej: DURANGO",
        btn_cancel: "Cancelar",
        btn_generate: "GENERAR DASHBOARD",
        btn_show_configured: "Mostrar campos configurados",
        btn_hide_configured: "Ocultar campos configurados",
        sidebar_filters: "Filtros",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTROS AVANZADOS",
        filter_years: "Años",
        filter_months: "Meses",
        filter_cats: "Categorías",
        sel_all: "Todos",
        sel_none: "Ninguno",
        sel_clear: "Limpiar",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Total",
        kpi_zona: "Zona",
        kpi_titulo: "TÍTULO",
        kpi_periodo: "Periodo",
        kpi_waiting: "Esperando...",
        kpi_filtered: "Filtrado",
        chart_timeline: "Evolución Temporal",
        chart_top: "Top Tipos",
        chart_hours: "Horas",
        chart_map: "Mapa",
        view_years: "Años",
        view_months: "Meses",
        view_quarters: "Trimestral",
        view_days: "Días Semanal",
        view_daily: "Diario",
        // Textos de Gráficos
        months_abbr: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        days_abbr: ['L-Lun', 'M-Mar', 'X-Mié', 'J-Jue', 'V-Vie', 'S-Sáb', 'D-Dom'],
        quarters: ['1º Trim', '2º Trim', '3º Trim', '4º Trim'],
        map_layers_title: "Mis Capas",
        map_filter_zone: "Filtrar datos por zona",
        map_no_layers: "Sin capas cargadas",
        btn_add_layer_title: "Subir GeoJSON",
        map_search_layers: "Buscar zona...",
        info_subtitle: "Análisis de datos filtrados",
        info_card_sintesis: "SÍNTESIS PRINCIPAL",
        info_lbl_total: "TOTAL REGISTROS",
        info_lbl_peak: "PICO DE ACTIVIDAD",
        info_lbl_day: "DÍA MÁS ACTIVO",
        info_lbl_trend: "Tendencia Temporal",
        info_lbl_top3: "Top 3 Categorías",
        info_lbl_dominance: "Dominancia",
        info_lbl_footer: "Generado por Eurocop Analytics AI",
        info_insight_text: "En <strong style='color:#11cdef'>{archivo}</strong>, la selección {cat} lidera las incidencias, representando el {percent}% del total.",
        info_trend_morning: "La actividad se concentra principalmente durante la mañana, sugiriendo patrones relacionados con la actividad laboral o comercial.",
        info_trend_afternoon: "Se observa un repunte significativo durante la tarde-noche, típico de actividades sociales y cierre de comercios.",
        info_trend_night: "La actividad nocturna es predominante, lo que podría requerir vigilancia especial en horarios de madrugada.",
        info_lbl_streets: "Ubicaciones Críticas",
        info_street_insight: "La mayor concentración de registros se localiza en {street}.",
        days_full: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        info_report_title: "Informe",
        btn_ai_infographic: "SÍNTESIS",
        btn_download_tip: "Descargar Imagen",
        btn_date_range_mode: "Modo: Desde - Hasta",
        btn_year_month_mode: "Modo: Año / Mes",
        btn_apply_filter: "Aplicar filtro",
        shift_morning: "Mañá",
        shift_afternoon: "Tarde",
        shift_night: "Noite",
        col_suma: "CAMPO SUMATORIO (Opcional)",
        col_suma_desc: "Columna numérica a sumar",
        kpi_suma: "Calculada",
        chart_suma_label: "Suma",
        shift_morning: "Mañana",
        shift_afternoon: "Tarde",
        shift_night: "Noche",
        col_suma: "CAMPO SUMATORIO (Opcional)",
        col_suma_desc: "Columna numérica a sumar (duración, importe, etc.)",
        kpi_suma: "Calculada",
        chart_suma_label: "Suma",
        clima_municipio_placeholder: "Municipio, Provincia",
        map_btn_3d: "Vista 3D",
        clima_municipio_placeholder: "Municipio, Provincia",
        map_btn_3d: "Vista 3D",
        info_lbl_stats: "KPIs",
        clima_period_days: "{n} día(s) con precipitación ({mm} mm acumulados)",
        clima_period_wind: "vento forte en {n} día(s) (máx. {kmh} km/h)",
        clima_period_snow: "nevada en {n} día(s) ({cm} cm)",
        clima_period_temp: "temperatura media {c}°C",
        clima_period_stable: "O período analizado presentou condicións meteorolóxicas estables.",
        clima_period_prefix: "O período analizado rexistrou",
        clima_corr_top: "O día de maior actividade foi {day} con {n} incidencias",
        clima_corr_with: "coincidindo con",
        clima_corr_none: "sen condición meteorolóxica adversa destacable",
        clima_corr_second: "Seguiulle {day} con {n} incidencias",
        clima_no_adverse: "Sen condición adversa",
        clima_stat_temp: "TEMPERATURA MEDIA",
        clima_stat_precip: "PRECIPITACIÓN TOTAL",
        clima_stat_wind: "VENTO MÁXIMO",
        clima_stat_snow: "NEVE ACUMULADA",
        clima_stat_days: "días analizados",
        clima_days_rain: "{n} día(s) con choiva",
        clima_days_wind: "{n} día(s) vento forte",
        clima_days_snow: "{n} día(s) con neve",
        clima_footer: "{n} días analizados · Open-Meteo API",
        clima_corr_label: "Correlación incidencias–clima:",
        clima_inc: "inc.",
        clima_dominancia: "dominancia",
        clima_lbl_temp_max: "Temp. Máx (°C)",
        clima_lbl_precip: "Precipitación (mm)",
        clima_lbl_wind: "Vento máx (km/h)",
        clima_lbl_snow: "Neve (cm)",
        d_lluvia_ligera: "Choiva lixeira",
        d_lluvia_mod: "Choiva moderada",
        d_lluvia_fuerte: "Choiva forte",
        d_lluvia_mfuerte: "Choiva moi forte",
        d_viento_calma: "Calma",
        d_viento_brisa: "Brisa moderada",
        d_viento_fuerte: "Vento forte",
        d_viento_mfuerte: "Vento moi forte",
        d_temp_helada: "Xeada",
        d_temp_frio: "Frío",
        d_temp_fresco: "Fresco",
        d_temp_agradable: "Agradable",
        d_temp_calor: "Calor",
        d_temp_extremo: "Calor extremo",
        d_nieve_ligera: "Nevada lixeira",
        d_nieve_mod: "Nevada moderada",
        d_nieve_intensa: "Nevada intensa",
        info_lbl_stats: "KPIs",
        clima_period_days: "{n} días con precipitación ({mm} mm acumulados)",
        clima_period_wind: "viento fuerte en {n} día(s) (máx. {kmh} km/h)",
        clima_period_snow: "nevada en {n} día(s) ({cm} cm)",
        clima_period_temp: "temperatura media {c}°C",
        clima_period_stable: "El período analizado presentó condiciones meteorológicas estables.",
        clima_period_prefix: "El período analizado registró",
        clima_corr_top: "El día de mayor actividad fue {day} con {n} incidencias",
        clima_corr_with: "coincidiendo con",
        clima_corr_none: "sin condición meteorológica adversa destacable",
        clima_corr_second: "Le siguió {day} con {n} incidencias",
        clima_no_adverse: "Sin condición adversa",
        clima_stat_temp: "TEMPERATURA MEDIA",
        clima_stat_precip: "PRECIPITACIÓN TOTAL",
        clima_stat_wind: "VIENTO MÁXIMO",
        clima_stat_snow: "NIEVE ACUMULADA",
        clima_stat_days: "días analizados",
        clima_days_rain: "{n} día(s) con lluvia",
        clima_days_wind: "{n} día(s) viento fuerte",
        clima_days_snow: "{n} día(s) con nieve",
        clima_footer: "{n} días analizados · Open-Meteo API",
        clima_corr_label: "Correlación incidencias–clima:",
        clima_inc: "inc.",
        clima_dominancia: "dominancia",
        clima_lbl_temp_max: "Temp. Máx (°C)",
        clima_lbl_precip: "Precipitación (mm)",
        clima_lbl_wind: "Viento máx (km/h)",
        clima_lbl_snow: "Nieve (cm)",
        d_lluvia_ligera: "Lluvia ligera",
        d_lluvia_mod: "Lluvia moderada",
        d_lluvia_fuerte: "Lluvia fuerte",
        d_lluvia_mfuerte: "Lluvia muy fuerte",
        d_viento_calma: "Calma",
        d_viento_brisa: "Brisa moderada",
        d_viento_fuerte: "Viento fuerte",
        d_viento_mfuerte: "Viento muy fuerte",
        d_temp_helada: "Helada",
        d_temp_frio: "Frío",
        d_temp_fresco: "Fresco",
        d_temp_agradable: "Agradable",
        d_temp_calor: "Calor",
        d_temp_extremo: "Calor extremo",
        d_nieve_ligera: "Nevada ligera",
        d_nieve_mod: "Nevada moderada",
        d_nieve_intensa: "Nevada intensa",
        clima_title: "METEOROLOXÍA",
        clima_panel_title: "Meteoroloxía Histórica",
        clima_activate: "Activar Clima",
        clima_active: "Clima Activo",
        clima_loading: "Cargando...",
        clima_error: "Erro - Reintentar",
        clima_var_temp: "🌡 Temperatura",
        clima_var_precip: "🌧 Precipitación",
        clima_var_wind: "💨 Vento",
        clima_var_snow: "❄ Neve",
        clima_var_all: "🌤 Todas",
        clima_mode_overlay: "Superposto",
        clima_mode_panel: "Panel separado",
        clima_reload_tip: "Recargar con estas coordenadas",
        clima_lat_tip: "Latitude (auto desde dataset)",
        clima_lon_tip: "Lonxitude (auto desde dataset)",
        clima_sintesis_title: "CORRELACIÓN METEOROLÓXICA",
        clima_title: "METEOROLOGÍA",
        clima_panel_title: "Meteorología Histórica",
        clima_activate: "Activar Clima",
        clima_active: "Clima Activo",
        clima_loading: "Cargando...",
        clima_error: "Error - Reintentar",
        clima_var_temp: "🌡 Temperatura",
        clima_var_precip: "🌧 Precipitación",
        clima_var_wind: "💨 Viento",
        clima_var_snow: "❄ Nieve",
        clima_var_all: "🌤 Todas",
        clima_mode_overlay: "Superpuesto",
        clima_mode_panel: "Panel separado",
        clima_reload_tip: "Recargar con estas coordenadas",
        clima_lat_tip: "Latitud (auto desde dataset)",
        clima_lon_tip: "Longitud (auto desde dataset)",
        clima_sintesis_title: "CORRELACIÓN METEOROLÓGICA",
        filter_date_from: "Fecha Desde",
        filter_date_to: "Fecha Hasta",
        filter_daymonth_from: "Desde",
        filter_daymonth_to: "Hasta",
        // Hotspot / Zona Crítica
        hotspot_no_gps: "Sin coordenadas GPS",
        hotspot_insufficient: "Datos insuficientes",
        hotspot_no_clusters: "No se detectan grupos",
        hotspot_focus: "Foco de Actividad",
        hotspot_points: "puntos",
        hotspot_epicenter: "Detectado epicentro con {count} incidentes cercanos.",
                // --- NUEVAS TRADUCCIONES MODAL ARCHIVO GRANDE ---
        modal_large_title: "Archivo Grande Detectado",
        modal_large_desc: "El archivo es superior a 1 MB. Para optimizar la velocidad, selecciona a partir de qué año quieres cargar los datos.",
        modal_large_label: "CARGAR DESDE EL AÑO:",
        modal_large_opt_from: "Desde",
        modal_large_opt_all: "Cargar todo el histórico (Más lento)",
        btn_continue: "CONTINUAR",
        alert_no_records: "No se encontraron registros para el año seleccionado.",
                narrative_title: "Análisis Narrativo",
        narrative_chronology: "Detalle Cronológico",
        narrative_summary: "Resumen Destacado",
        narrative_max: "Mayor Actividad",
        narrative_min: "Menor Actividad",
        narrative_avg: "Promedio del Periodo",
        narrative_total_period: "Total en este periodo",
        narrative_records: "registros",
        extra_filters_title: "FILTROS EXTRA",
        extra_filter_1: "FILTRO EXTRA 1",
        extra_filter_2: "FILTRO EXTRA 2"
    },
    eu: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALITIKA",
        no_file: "FITXATEGIRIK EZ",
        kpi_reg: "ERREG",
        lbl_year: "URTEA",
        lbl_month: "HILA",
        lbl_cat: "KAT",
        upload_title: "Datuen Karga",
        upload_desc: "Igo zure Excel (.xlsx) edo CSV fitxategia.",
        upload_drop: "ARRASTRATU EDO UKITU IGOTZEKO",
        upload_mobile: "Mugikorrekin bateragarria",
        btn_manual: "Eskuliburua",
        btn_updates: "Eguneraketak",
        btn_memorias: "Memoriak",
        brand_powered: "Powered by",
        config_title: "KONFIGURAZIOA",
        config_desc: "Lotu zure fitxategiko zutabeak.",
        col_id: "KONTAGAILUA / ID",
        col_lat: "LATITUDEA (Y)",
        col_lon: "LONGITUDEA (X)",
        col_date: "DATA (Nahitaezkoa)",
        col_time: "ORDUA (Aukerakoa)",
        col_street: "KALEA / HELBIDEA (Aukerakoa)",
        col_cat: "KATEGORIA / MOTA",
        col_cat_desc: "Hautatu intzidentzia mota definitzen duen zutabea.",
        col_loc: "HERRIA (Aukerakoa)",
        col_loc_desc: "Idatzi izena eremua behartzeko. Utzi hutsik GPSrako.",
        col_loc_placeholder: "Adib: DURANGO",
        btn_cancel: "Utzi",
        btn_generate: "DASHBOARDA SORTU",
        btn_show_configured: "Erakutsi konfiguratutako eremuak",
        btn_hide_configured: "Ezkutatu konfiguratutako eremuak",
        sidebar_filters: "Iragazkiak",
        btn_export: "PDF-RA ESPORTATU",
        filter_header: "IRAGAZKI AURRERATUAK",
        filter_years: "Urteak",
        filter_months: "Hilabeteak",
        filter_cats: "Kategoriak",
        sel_all: "Denak",
        sel_none: "Bat ere ez",
        sel_clear: "Garbitu",
        sel_select: "Hautatu...",
        kpi_expedientes: "Guztira",
        kpi_zona: "Eremua",
        kpi_titulo: "IZENBURUA",
        kpi_periodo: "Epea",
        kpi_waiting: "Zain...",
        kpi_filtered: "Iragazita",
        chart_timeline: "Denbora Bilakaera",
        chart_top: "Mota Nagusiak",
        chart_hours: "Orduak",
        chart_map: "Mapa",
        view_years: "Urteak",
        view_months: "Hilabeteak",
        view_quarters: "Hiruhilekoa",
        view_days: "Asteko Egunak",
        view_daily: "Egunez egun",
        loading_msg: "Fitxategia prozesatzen...",
        months_abbr: ['Urt', 'Ots', 'Mar', 'Api', 'Mai', 'Eka', 'Uzt', 'Abu', 'Ira', 'Urr', 'Aza', 'Abe'],
        days_abbr: ['Al-Astelehena', 'Ar-Asteartea', 'Az-Asteazkena', 'Og-Osteguna', 'Ol-Ostirala', 'Lr-Larunbata', 'Ig-Igandea'],
        quarters: ['1. Hiruh', '2. Hiruh', '3. Hiruh', '4. Hiruh'],
        map_layers_title: "Nire Geruzak",
        map_filter_zone: "Datuak eremuka iragazi",
        map_no_layers: "Kargatutako geruzarik ez",
        btn_add_layer_title: "Igo GeoJSON",
        map_search_layers: "Bilatu eremua...",
        // PDF Sintesis
        info_subtitle: "Filtratutako datuen analisia",
        info_card_sintesis: "SINTESI NAGUSIA",
        info_lbl_total: "ERREGISTROAK GUZTIRA",
        info_lbl_peak: "JARDUERA GORENA",
        info_lbl_day: "EGUN AKTIBOENA",
        info_lbl_trend: "Denbora-joera",
        info_lbl_top3: "3 Kategoria Nagusiak",
        info_lbl_dominance: "Dominantzia",
        info_lbl_footer: "Eurocop Analytics AI-k sortua",
        info_insight_text: "<strong style='color:#11cdef'>{archivo}</strong> fitxategian, {cat} hautaketa da nagusi gertakarietan, guztizkoaren %{percent} izanda.",
        info_trend_morning: "Jarduerea goizean kontzentratzen da nagusiki, lan- edo merkataritza-jarduerekin lotutako ereduen ondorioz.",
        info_trend_afternoon: "Arratsalde-gauean gorakada nabarmena ikusten da, gizarte-jarduerekin eta denden itxierarekin lotua.",
        info_trend_night: "Gaueko jarduera nagusia da, eta horrek zainketa berezia behar dezake goizaldean.",
        info_lbl_streets: "Kokapen Kritikoak",
        info_street_insight: "Erregistro gehienak {street} kalean pilatzen dira.",
        days_full: ['Igandea', 'Astelehena', 'Asteartea', 'Asteazkena', 'Osteguna', 'Ostirala', 'Larunbata'],
        info_report_title: "Txostena",
        btn_ai_infographic: "SINTESIA",
        btn_download_tip: "Irudia Deskargatu",
        btn_date_range_mode: "Modua: Noiztik - Noiz arte",
        btn_year_month_mode: "Modua: Urtea / Hila",
        btn_apply_filter: "Iragazkia aplikatu",
        shift_morning: "Goizaldea",
        shift_afternoon: "Arratsaldea",
        shift_night: "Gaua",
        col_suma: "BATUKETA EREMUA (Aukerakoa)",
        col_suma_desc: "Batuketa eremu numerikoa",
        kpi_suma: "Kalkulatua",
        chart_suma_label: "Batura",
        clima_municipio_placeholder: "Udalerria, Probintzia",
        map_btn_3d: "3D ikuspegia",
        info_lbl_stats: "KPIak",
        clima_period_days: "{n} egun prezipitazioarekin ({mm} mm metatuta)",
        clima_period_wind: "haize indartsua {n} egunetan (máx. {kmh} km/h)",
        clima_period_snow: "elurra {n} egunetan ({cm} cm)",
        clima_period_temp: "batez besteko tenperatura {c}°C",
        clima_period_stable: "Aztertutako aldiak baldintza meteorologiko egonkorrak aurkeztu zituen.",
        clima_period_prefix: "Aztertutako aldiak erregistratu zuen",
        clima_corr_top: "Jardunaldi handieneko eguna {day} izan zen {n} gertakarirekin",
        clima_corr_with: "bat eginez",
        clima_corr_none: "eguraldi kontrako baldintza nabarmenik gabe",
        clima_corr_second: "{day} jarraitu zion {n} gertakarirekin",
        clima_no_adverse: "Kontrako baldintza gabe",
        clima_stat_temp: "BATEZ BESTEKO TENPERATURA",
        clima_stat_precip: "PREZIPITAZIO TOTALA",
        clima_stat_wind: "HAIZE MAXIMOA",
        clima_stat_snow: "ELUR METAKETA",
        clima_stat_days: "egun aztertuta",
        clima_days_rain: "{n} egun eurirekin",
        clima_days_wind: "{n} egun haize indartsurekin",
        clima_days_snow: "{n} egun elurrekin",
        clima_footer: "{n} egun aztertuta · Open-Meteo API",
        clima_corr_label: "Gertakariak–klima korrelazioa:",
        clima_inc: "gert.",
        clima_dominancia: "nagusitasuna",
        clima_lbl_temp_max: "Tenp. Max (°C)",
        clima_lbl_precip: "Prezipitazioa (mm)",
        clima_lbl_wind: "Haize max (km/h)",
        clima_lbl_snow: "Elurra (cm)",
        d_lluvia_ligera: "Euri arina",
        d_lluvia_mod: "Euri moderatua",
        d_lluvia_fuerte: "Euri gogorra",
        d_lluvia_mfuerte: "Euri oso gogorra",
        d_viento_calma: "Lasai",
        d_viento_brisa: "Haize arina",
        d_viento_fuerte: "Haize indartsua",
        d_viento_mfuerte: "Haize oso indartsua",
        d_temp_helada: "Izotza",
        d_temp_frio: "Hotza",
        d_temp_fresco: "Fresko",
        d_temp_agradable: "Atsegingarria",
        d_temp_calor: "Beroa",
        d_temp_extremo: "Bero muturrekoa",
        d_nieve_ligera: "Elur arina",
        d_nieve_mod: "Elur moderatua",
        d_nieve_intensa: "Elur gogorra",
        clima_title: "METEOROLOGIA",
        clima_panel_title: "Meteorologia Històrica",
        clima_panel_title: "Meteorologia Historikoa",
        clima_activate: "Klima Aktibatu",
        clima_active: "Klima Aktibo",
        clima_loading: "Kargatzen...",
        clima_error: "Errorea - Saiatu berriro",
        clima_var_temp: "🌡 Tenperatura",
        clima_var_precip: "🌧 Prezipitazioa",
        clima_var_wind: "💨 Haizea",
        clima_var_snow: "❄ Elurra",
        clima_var_all: "🌤 Denak",
        clima_mode_overlay: "Gainjarrita",
        clima_mode_panel: "Panel berezia",
        clima_reload_tip: "Kargatu berriro koordenatu hauekin",
        clima_lat_tip: "Latitudea (datasetatik auto)",
        clima_lon_tip: "Longitudea (datasetatik auto)",
        clima_sintesis_title: "METEOROLOGIA KORRELAZIOA",
        filter_date_from: "Data Noiztik",
        filter_date_to: "Data Noiz arte",
        filter_daymonth_from: "Noiztik",
        filter_daymonth_to: "Noiz arte",
        // Hotspot / Zona Crítica
        hotspot_no_gps: "GPS koordenatuak ez dituen",
        hotspot_insufficient: "Datu gutxiak",
        hotspot_no_clusters: "Taldeak ez ikusten",
        hotspot_focus: "Jarduera Gunea",
        hotspot_points: "puntuak",
        hotspot_epicenter: "Epicentro hautematen da {count} inguruko gertakariekin.",
        // --- NUEVAS TRADUCCIONES MODAL ARCHIVO GRANDE ---
        modal_large_title: "Fitxategi Handia Atzeman Da",
        modal_large_desc: "Fitxategia 1 MB baino handiagoa da. Abiadura optimizatzeko, hautatu zein urtetatik aurrera kargatu nahi dituzun datuak.",
        modal_large_label: "KARGATU URTE HONETATIK:",
        modal_large_opt_from: "Noiztik:",
        modal_large_opt_all: "Kargatu historiko osoa (Motelagoa)",
        btn_continue: "JARRAITU",
        alert_no_records: "Ez da erregistrorik aurkitu hautatutako urterako.",
        narrative_title: "Analisi Narratiboa",
        narrative_chronology: "Xehetasun Kronologikoa",
        narrative_summary: "Laburpen Nabarmena",
        narrative_max: "Jarduera Handiena",
        narrative_min: "Jarduera Txikiena",
        narrative_avg: "Aldiaren Batezbestekoa",
        narrative_total_period: "Guztira aldi honetan",
        narrative_records: "erregistro",
        extra_filters_title: "IRAGAZKI EXTRAK",
        extra_filter_1: "1. IRAGAZKI EXTRA",
        extra_filter_2: "2. IRAGAZKI EXTRA"
    },
    ca: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SENSE ARXIU",
        kpi_reg: "REG",
        lbl_year: "ANY",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Càrrega de Dades",
        upload_desc: "Puja el teu arxiu Excel (.xlsx) o CSV.",
        upload_drop: "ARROSSEGAR O TOCAR PER PUJAR",
        upload_mobile: "Compatible amb mòbils",
        btn_manual: "Veure Manual",
        btn_updates: "Actualitzacions",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓ",
        config_desc: "Vincula les columnes del teu arxiu.",
        col_id: "COMPTADOR / ID",
        col_lat: "LATITUD (Y)",
        col_lon: "LONGITUD (X)",
        col_date: "DATA (Obligatori)",
        col_time: "HORA (Opcional)",
        col_street: "CARRER / ADREÇA (Opcional)",
        col_cat: "CATEGORIA / TIPUS",
        col_cat_desc: "Selecciona la columna que defineix el tipus d'incidència.",
        col_loc: "LOCALITAT (Opcional)",
        col_loc_desc: "Escriu el nom per forçar la zona. Deixa-ho buit per GPS.",
        col_loc_placeholder: "Ex: DURANGO",
        btn_cancel: "Cancel·lar",
        btn_generate: "GENERAR DASHBOARD",
        btn_show_configured: "Mostrar camps configurats",
        btn_hide_configured: "Ocultar camps configurats",
        sidebar_filters: "Filtres",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTRES AVANÇATS",
        filter_years: "Anys",
        filter_months: "Mesos",
        filter_cats: "Categories",
        sel_all: "Tots",
        sel_none: "Cap",
        sel_clear: "Netejar",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Total",
        kpi_zona: "Zona",
        kpi_titulo: "TÍTOL",
        kpi_periodo: "Període",
        kpi_waiting: "Esperant...",
        kpi_filtered: "Filtrat",
        chart_timeline: "Evolució Temporal",
        chart_top: "Top Tipus",
        chart_hours: "Hores",
        chart_map: "Mapa",
        view_years: "Anys",
        view_months: "Mesos",
        view_quarters: "Trimestral",
        view_days: "Dies Setmanal",
        view_daily: "Diari",
        loading_msg: "Processant l'arxiu...",
        months_abbr: ['Gen', 'Feb', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Des'],
        days_abbr: ['Dl-Dilluns', 'Dm-Dimarts', 'Dc-Dimecres', 'Dj-Dijous', 'Dv-Divendres', 'Ds-Dissabte', 'Dg-Diumenge'],
        quarters: ['1r Trim', '2n Trim', '3r Trim', '4t Trim'],
        map_layers_title: "Les Meves Capes",
        map_filter_zone: "Filtrar dades per zona",
        map_no_layers: "Sense capes carregades",
        btn_add_layer_title: "Pujar GeoJSON",
        map_search_layers: "Cercar zona...",
        // PDF Sintesis
        info_subtitle: "Anàlisi de dades filtrades",
        info_card_sintesis: "SÍNTESI PRINCIPAL",
        info_lbl_total: "TOTAL REGISTRES",
        info_lbl_peak: "PICS D'ACTIVITAT",
        info_lbl_day: "DIA MÉS ACTIU",
        info_lbl_trend: "Tendència Temporal",
        info_lbl_top3: "Top 3 Categories",
        info_lbl_dominance: "Dominància",
        info_lbl_footer: "Generat per Eurocop Analytics AI",
        info_insight_text: "A <strong style='color:#11cdef'>{archivo}</strong>, la selecció {cat} lidera les incidències, representant el {percent}% del total.",
        info_trend_morning: "L'activitat es concentra principalment durant el matí, suggerint patrons relacionats amb l'activitat laboral o comercial.",
        info_trend_afternoon: "S'observa un repunt significatiu durant la tarda-nit, típic d'activitats socials i tancament de comerços.",
        info_trend_night: "L'activitat nocturna és predominant, la qual cosa podria requerir vigilància especial en horaris de matinada.",
        info_lbl_streets: "Ubicacions Crítiques",
        info_street_insight: "La major concentració de registres es localitza a {street}.",
        days_full: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],
        info_report_title: "Informe",
        btn_ai_infographic: "SÍNTESI",
        btn_download_tip: "Descarregar Imatge",
        btn_date_range_mode: "Mode: Des de - Fins a",
        btn_year_month_mode: "Mode: Any / Mes",
        btn_apply_filter: "Aplicar filtre",
        shift_morning: "Matí",
        shift_afternoon: "Tarda",
        shift_night: "Nit",
        col_suma: "CAMP SUMATORI (Opcional)",
        col_suma_desc: "Columna numèrica a sumar",
        kpi_suma: "Calculada",
        chart_suma_label: "Suma",
        clima_municipio_placeholder: "Municipi, Província",
        map_btn_3d: "Vista 3D",
        info_lbl_stats: "KPIs",
        clima_period_days: "{n} dia(es) amb precipitació ({mm} mm acumulats)",
        clima_period_wind: "vent fort en {n} dia(es) (màx. {kmh} km/h)",
        clima_period_snow: "nevada en {n} dia(es) ({cm} cm)",
        clima_period_temp: "temperatura mitjana {c}°C",
        clima_period_stable: "El període analitzat va presentar condicions meteorològiques estables.",
        clima_period_prefix: "El període analitzat va registrar",
        clima_corr_top: "El dia de major activitat va ser {day} amb {n} incidències",
        clima_corr_with: "coincidint amb",
        clima_corr_none: "sense condició meteorològica adversa destacable",
        clima_corr_second: "El va seguir {day} amb {n} incidències",
        clima_no_adverse: "Sense condició adversa",
        clima_stat_temp: "TEMPERATURA MITJANA",
        clima_stat_precip: "PRECIPITACIÓ TOTAL",
        clima_stat_wind: "VENT MÀXIM",
        clima_stat_snow: "NEU ACUMULADA",
        clima_stat_days: "dies analitzats",
        clima_days_rain: "{n} dia(es) amb pluja",
        clima_days_wind: "{n} dia(es) vent fort",
        clima_days_snow: "{n} dia(es) amb neu",
        clima_footer: "{n} dies analitzats · Open-Meteo API",
        clima_corr_label: "Correlació incidències–clima:",
        clima_inc: "inc.",
        clima_dominancia: "dominància",
        clima_lbl_temp_max: "Temp. Màx (°C)",
        clima_lbl_precip: "Precipitació (mm)",
        clima_lbl_wind: "Vent màx (km/h)",
        clima_lbl_snow: "Neu (cm)",
        d_lluvia_ligera: "Pluja lleugera",
        d_lluvia_mod: "Pluja moderada",
        d_lluvia_fuerte: "Pluja forta",
        d_lluvia_mfuerte: "Pluja molt forta",
        d_viento_calma: "Calma",
        d_viento_brisa: "Brisa moderada",
        d_viento_fuerte: "Vent fort",
        d_viento_mfuerte: "Vent molt fort",
        d_temp_helada: "Gelada",
        d_temp_frio: "Fred",
        d_temp_fresco: "Fresc",
        d_temp_agradable: "Agradable",
        d_temp_calor: "Calor",
        d_temp_extremo: "Calor extrem",
        d_nieve_ligera: "Nevada lleugera",
        d_nieve_mod: "Nevada moderada",
        d_nieve_intensa: "Nevada intensa",
        clima_title: "METEOROLOGIA",
        clima_panel_title: "Meteorologia Històrica",
        clima_panel_title: "Meteorologia Historikoa",
        clima_activate: "Activar Clima",
        clima_active: "Clima Actiu",
        clima_loading: "Carregant...",
        clima_error: "Error - Torna-ho a intentar",
        clima_var_temp: "🌡 Temperatura",
        clima_var_precip: "🌧 Precipitació",
        clima_var_wind: "💨 Vent",
        clima_var_snow: "❄ Neu",
        clima_var_all: "🌤 Totes",
        clima_mode_overlay: "Superposat",
        clima_mode_panel: "Panell separat",
        clima_reload_tip: "Recarregar amb aquestes coordenades",
        clima_lat_tip: "Latitud (auto des del dataset)",
        clima_lon_tip: "Longitud (auto des del dataset)",
        clima_sintesis_title: "CORRELACIÓ METEOROLÒGICA",
        filter_date_from: "Data Des de",
        filter_date_to: "Data Fins a",
        filter_daymonth_from: "Des de",
        filter_daymonth_to: "Fins a",
        // Hotspot / Zona Crítica
        hotspot_no_gps: "Sense coordenades GPS",
        hotspot_insufficient: "Dades insuficients",
        hotspot_no_clusters: "No es detecten grups",
        hotspot_focus: "Focus d'Activitat",
        hotspot_points: "punts",
        hotspot_epicenter: "Epicentre detectat amb {count} incidents propellers.",
        // --- NUEVAS TRADUCCIONES MODAL ARCHIVO GRANDE ---
        modal_large_title: "Arxiu Gran Detectat",
        modal_large_desc: "L'arxiu és superior a 1 MB. Per optimitzar la velocitat, selecciona a partir de quin any vols carregar les dades.",
        modal_large_label: "CARREGAR DES DE L'ANY:",
        modal_large_opt_from: "Des de",
        modal_large_opt_all: "Carregar tot l'històric (Més lent)",
        btn_continue: "CONTINUAR",
        alert_no_records: "No s'han trobat registres per a l'any seleccionat.",
        narrative_title: "Anàlisi Narrativa",
        narrative_chronology: "Detall Cronològic",
        narrative_summary: "Resum Destacat",
        narrative_max: "Major Activitat",
        narrative_min: "Menor Activitat",
        narrative_avg: "Mitjana del Període",
        narrative_total_period: "Total en aquest període",
        narrative_records: "registres",
        extra_filters_title: "FILTRES EXTRA",
        extra_filter_1: "FILTRE EXTRA 1",
        extra_filter_2: "FILTRE EXTRA 2"
    },
    gl: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SEN ARQUIVO",
        kpi_reg: "REX",
        lbl_year: "ANO",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Carga de Datos",
        upload_desc: "Sube o teu arquivo Excel (.xlsx) o CSV.",
        upload_drop: "ARRASTRAR OU TOCAR PARA SUBIR",
        upload_mobile: "Compatible con móbiles",
        btn_manual: "Ver Manual",
        btn_updates: "Actualizacións",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓN",
        config_desc: "Vincula as columnas do teu arquivo.",
        col_id: "CONTADOR / ID",
        col_lat: "LATITUDE (Y)",
        col_lon: "LONXITUDE (X)",
        col_date: "DATA (Obrigatorio)",
        col_time: "HORA (Opcional)",
        col_street: "RÚA / ENDEREZO (Opcional)",
        col_cat: "CATEGORÍA / TIPO",
        col_cat_desc: "Selecciona a columna que define o tipo de incidencia.",
        col_loc: "LOCALIDADE (Opcional)",
        col_loc_desc: "Escribe o nome para forzar a zona. Deixao baleiro para GPS.",
        col_loc_placeholder: "Ex: DURANGO",
        btn_cancel: "Cancelar",
        btn_generate: "XERAR DASHBOARD",
        btn_show_configured: "Mostrar campos configurados",
        btn_hide_configured: "Ocultar campos configurados",
        sidebar_filters: "Filtros",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTROS AVANZADOS",
        filter_years: "Anos",
        filter_months: "Meses",
        filter_cats: "Categorías",
        sel_all: "Todos",
        sel_none: "Ningún",
        sel_clear: "Limpar",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Total",
        kpi_zona: "Zona",
        kpi_titulo: "TÍTULO",
        kpi_periodo: "Período",
        kpi_waiting: "Agardando...",
        kpi_filtered: "Filtrado",
        chart_timeline: "Evolución Temporal",
        chart_top: "Top Tipos",
        chart_hours: "Horas",
        chart_map: "Mapa",
        view_years: "Anos",
        view_months: "Meses",
        view_quarters: "Trimestral",
        view_days: "Días Semanal",
        view_daily: "Diario",
        loading_msg: "Procesando arquivo...",
        months_abbr: ['Xan', 'Feb', 'Mar', 'Abr', 'Mai', 'Xuñ', 'Xul', 'Ago', 'Set', 'Out', 'Nov', 'Dec'],
        days_abbr: ['L-Luns', 'M-Martes', 'X-Mércores', 'X-Xoves', 'V-Venres', 'S-Sábado', 'D-Domingo'],
        quarters: ['1º Trim', '2º Trim', '3º Trim', '4º Trim'],
        map_layers_title: "As Miñas Capas",
        map_filter_zone: "Filtrar datos por zona",
        map_no_layers: "Sen capas cargadas",
        btn_add_layer_title: "Subir GeoJSON",
        map_search_layers: "Buscar zona...",
        // PDF Sintesis
        info_subtitle: "Análise de datos filtrados",
        info_card_sintesis: "SÍNTESE PRINCIPAL",
        info_lbl_total: "TOTAL REXISTROS",
        info_lbl_peak: "PICO DE ACTIVIDADE",
        info_lbl_day: "DÍA MÁIS ACTIVO",
        info_lbl_trend: "Tendencia Temporal",
        info_lbl_top3: "Top 3 Categorías",
        info_lbl_dominance: "Dominancia",
        info_lbl_footer: "Xerado por Eurocop Analytics AI",
        info_insight_text: "En <strong style='color:#11cdef'>{archivo}</strong>, a selección {cat} lidera as incidencias, representando o {percent}% do total.",
        info_trend_morning: "A actividade concéntrase principalmente durante a mañá, suxerindo patróns relacionados coa actividade laboral ou comercial.",
        info_trend_afternoon: "Obsérvase un repunte significativo durante a tarde-noite, típico de actividades sociais e peche de comercios.",
        info_trend_night: "A actividade nocturna é predominante, o que podería requirir vixilancia especial en horarios de madrugada.",
        info_lbl_streets: "Localizacións Críticas",
        info_street_insight: "A maior concentración de rexistros localízase en {street}.",
        days_full: ['Domingo', 'Luns', 'Martes', 'Mércores', 'Xoves', 'Venres', 'Sábado'],
        info_report_title: "Informe",
        btn_ai_infographic: "SÍNTESE",
        btn_download_tip: "Descargar Imaxe",
        btn_date_range_mode: "Modo: Desde - Ata",
        btn_year_month_mode: "Modo: Ano / Mes",
        btn_apply_filter: "Aplicar filtro",
        filter_date_from: "Data Desde",
        filter_date_to: "Data Ata",
        filter_daymonth_from: "Desde",
        filter_daymonth_to: "Ata",
        // Hotspot / Zona Crítica
        hotspot_no_gps: "Sen coordenadas GPS",
        hotspot_insufficient: "Datos insuficientes",
        hotspot_no_clusters: "Non se detectan grupos",
        hotspot_focus: "Foco de Actividade",
        hotspot_points: "puntos",
        hotspot_epicenter: "Epicentro detectado con {count} incidentes cercanos.",
        // --- NUEVAS TRADUCCIONES MODAL ARCHIVO GRANDE ---
        modal_large_title: "Arquivo Grande Detectado",
        modal_large_desc: "O arquivo é superior a 1 MB. Para optimizar a velocidade, selecciona a partir de que ano queres cargar os datos.",
        modal_large_label: "CARGAR DESDE O ANO:",
        modal_large_opt_from: "Desde",
        modal_large_opt_all: "Cargar todo o histórico (Máis lento)",
        btn_continue: "CONTINUAR",
        alert_no_records: "Non se atoparon rexistros para o ano seleccionado.",
        narrative_title: "Análise Narrativa",
        narrative_chronology: "Detalle Cronolóxico",
        narrative_summary: "Resumo Destacado",
        narrative_max: "Maior Actividade",
        narrative_min: "Menor Actividade",
        narrative_avg: "Media do Período",
        narrative_total_period: "Total neste período",
        narrative_records: "rexistros",
        extra_filters_title: "FILTROS EXTRA",
        extra_filter_1: "FILTRO EXTRA 1",
        extra_filter_2: "FILTRO EXTRA 2"
    }
};