const translations = {
    es: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SIN ARCHIVO",
        kpi_reg: "REG",
        lbl_year: "AÑO",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Carga de Datos",
        upload_desc: "Sube tu archivo Excel (.xlsx) o CSV.",
        upload_drop: "ARRASTRAR O TOCAR PARA SUBIR",
        upload_mobile: "Compatible con móviles",
        btn_manual: "Ver Manual",
        btn_updates: "Actualizaciones",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓN",
        config_desc: "Vincula las columnas de tu archivo.",
        col_id: "CONTADOR / ID",
        col_lat: "LATITUD (Y)",
        col_lon: "LONGITUD (X)",
        col_date: "FECHA (Obligatorio)",
        col_time: "HORA (Opcional)",
        col_cat: "CATEGORÍA / TIPO",
        col_cat_desc: "Selecciona la columna que define el tipo de incidencia.",
        col_loc: "LOCALIDAD (Opcional)",
        col_loc_desc: "Escribe el nombre para forzar la zona. Déjalo vacío para GPS.",
        col_loc_placeholder: "Ej: DURANGO",
        btn_cancel: "Cancelar",
        btn_generate: "GENERAR DASHBOARD",
        sidebar_filters: "Filtros",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTROS AVANZADOS",
        filter_years: "Años",
        filter_months: "Meses",
        filter_cats: "Categorías",
        sel_all: "Todos",
        sel_none: "Ninguno",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Expedientes",
        kpi_zona: "Zona",
        kpi_periodo: "Periodo",
        kpi_waiting: "Esperando...",
        kpi_filtered: "Filtrado",
        chart_timeline: "Evolución Temporal",
        chart_top: "Top Tipos",
        chart_hours: "Horas",
        chart_map: "Mapa",
        view_years: "Vista: Años",
        view_months: "Vista: Meses",
        view_quarters: "Vista: Trimestral",
        view_days: "Vista: Días Semanal",
        loading_msg: "Procesando archivo...",
        // Textos de Gráficos
        months_abbr: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        days_abbr: ['L-Lun', 'M-Mar', 'X-Mié', 'J-Jue', 'V-Vie', 'S-Sáb', 'D-Dom'],
        quarters: ['1º Trim', '2º Trim', '3º Trim', '4º Trim']
    },
    eu: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALITIKA",
        no_file: "FITXATEGIRIK EZ",
        kpi_reg: "ERREG",
        lbl_year: "URTEA",
        lbl_month: "HILA",
        lbl_cat: "KAT",
        upload_title: "Datuen Karga",
        upload_desc: "Igo zure Excel (.xlsx) edo CSV fitxategia.",
        upload_drop: "ARRASTRATU EDO UKITU IGOTZEKO",
        upload_mobile: "Mugikorrekin bateragarria",
        btn_manual: "Eskuliburua",
        btn_updates: "Eguneraketak",
        brand_powered: "Powered by",
        config_title: "KONFIGURAZIOA",
        config_desc: "Lotu zure fitxategiko zutabeak.",
        col_id: "KONTAGAILUA / ID",
        col_lat: "LATITUDEA (Y)",
        col_lon: "LONGITUDEA (X)",
        col_date: "DATA (Nahitaezkoa)",
        col_time: "ORDUA (Aukerakoa)",
        col_cat: "KATEGORIA / MOTA",
        col_cat_desc: "Hautatu intzidentzia mota definitzen duen zutabea.",
        col_loc: "HERRIA (Aukerakoa)",
        col_loc_desc: "Idatzi izena eremua behartzeko. Utzi hutsik GPSrako.",
        col_loc_placeholder: "Adib: DURANGO",
        btn_cancel: "Utzi",
        btn_generate: "DASHBOARDA SORTU",
        sidebar_filters: "Iragazkiak",
        btn_export: "PDF-RA ESPORTATU",
        filter_header: "IRAGAZKI AURRERATUAK",
        filter_years: "Urteak",
        filter_months: "Hilabeteak",
        filter_cats: "Kategoriak",
        sel_all: "Denak",
        sel_none: "Bat ere ez",
        sel_select: "Hautatu...",
        kpi_expedientes: "Espedienteak",
        kpi_zona: "Eremua",
        kpi_periodo: "Epea",
        kpi_waiting: "Zain...",
        kpi_filtered: "Iragazita",
        chart_timeline: "Denbora Bilakaera",
        chart_top: "Mota Nagusiak",
        chart_hours: "Orduak",
        chart_map: "Mapa",
        view_years: "Ikuspegia: Urteak",
        view_months: "Ikuspegia: Hilabeteak",
        view_quarters: "Ikuspegia: Hiruhilekoa",
        view_days: "Ikuspegia: Asteko Egunak",
        loading_msg: "Fitxategia prozesatzen...",
        months_abbr: ['Urt', 'Ots', 'Mar', 'Api', 'Mai', 'Eka', 'Uzt', 'Abu', 'Ira', 'Urr', 'Aza', 'Abe'],
        days_abbr: ['Al-Astelehena', 'Ar-Asteartea', 'Az-Asteazkena', 'Og-Osteguna', 'Ol-Ostirala', 'Lr-Larunbata', 'Ig-Igandea'],
        quarters: ['1. Hiruh', '2. Hiruh', '3. Hiruh', '4. Hiruh']
    },
    ca: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SENSE ARXIU",
        kpi_reg: "REG",
        lbl_year: "ANY",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Càrrega de Dades",
        upload_desc: "Puja el teu arxiu Excel (.xlsx) o CSV.",
        upload_drop: "ARROSSEGAR O TOCAR PER PUJAR",
        upload_mobile: "Compatible amb mòbils",
        btn_manual: "Veure Manual",
        btn_updates: "Actualitzacions",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓ",
        config_desc: "Vincula les columnes del teu arxiu.",
        col_id: "COMPTADOR / ID",
        col_lat: "LATITUD (Y)",
        col_lon: "LONGITUD (X)",
        col_date: "DATA (Obligatori)",
        col_time: "HORA (Opcional)",
        col_cat: "CATEGORIA / TIPUS",
        col_cat_desc: "Selecciona la columna que defineix el tipus d'incidència.",
        col_loc: "LOCALITAT (Opcional)",
        col_loc_desc: "Escriu el nom per forçar la zona. Deixa-ho buit per GPS.",
        col_loc_placeholder: "Ex: DURANGO",
        btn_cancel: "Cancel·lar",
        btn_generate: "GENERAR DASHBOARD",
        sidebar_filters: "Filtres",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTRES AVANÇATS",
        filter_years: "Anys",
        filter_months: "Mesos",
        filter_cats: "Categories",
        sel_all: "Tots",
        sel_none: "Cap",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Expedients",
        kpi_zona: "Zona",
        kpi_periodo: "Període",
        kpi_waiting: "Esperant...",
        kpi_filtered: "Filtrat",
        chart_timeline: "Evolució Temporal",
        chart_top: "Top Tipus",
        chart_hours: "Hores",
        chart_map: "Mapa",
        view_years: "Vista: Anys",
        view_months: "Vista: Mesos",
        view_quarters: "Vista: Trimestral",
        view_days: "Vista: Dies Setmanal",
        months_abbr: ['Gen', 'Feb', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Des'],
        days_abbr: ['Dl-Dilluns', 'Dm-Dimarts', 'Dc-Dimecres', 'Dj-Dijous', 'Dv-Divendres', 'Ds-Dissabte', 'Dg-Diumenge'],
        quarters: ['1r Trim', '2n Trim', '3r Trim', '4t Trim']
    },
    gl: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SEN ARQUIVO",
        kpi_reg: "REX",
        lbl_year: "ANO",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Carga de Datos",
        upload_desc: "Sube o teu arquivo Excel (.xlsx) o CSV.",
        upload_drop: "ARRASTRAR OU TOCAR PARA SUBIR",
        upload_mobile: "Compatible con móbiles",
        btn_manual: "Ver Manual",
        btn_updates: "Actualizacións",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓN",
        config_desc: "Vincula as columnas do teu arquivo.",
        col_id: "CONTADOR / ID",
        col_lat: "LATITUDE (Y)",
        col_lon: "LONXITUDE (X)",
        col_date: "DATA (Obrigatorio)",
        col_time: "HORA (Opcional)",
        col_cat: "CATEGORÍA / TIPO",
        col_cat_desc: "Selecciona a columna que define o tipo de incidencia.",
        col_loc: "LOCALIDADE (Opcional)",
        col_loc_desc: "Escribe o nome para forzar a zona. Deixao baleiro para GPS.",
        col_loc_placeholder: "Ex: DURANGO",
        btn_cancel: "Cancelar",
        btn_generate: "XERAR DASHBOARD",
        sidebar_filters: "Filtros",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTROS AVANZADOS",
        filter_years: "Anos",
        filter_months: "Meses",
        filter_cats: "Categorías",
        sel_all: "Todos",
        sel_none: "Ningún",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Expedientes",
        kpi_zona: "Zona",
        kpi_periodo: "Período",
        kpi_waiting: "Agardando...",
        kpi_filtered: "Filtrado",
        chart_timeline: "Evolución Temporal",
        chart_top: "Top Tipos",
        chart_hours: "Horas",
        chart_map: "Mapa",
        view_years: "Vista: Anos",
        view_months: "Vista: Meses",
        view_quarters: "Vista: Trimestral",
        view_days: "Vista: Días Semanal",
        loading_msg: "Procesando arquivo...",
        months_abbr: ['Xan', 'Feb', 'Mar', 'Abr', 'Mai', 'Xuñ', 'Xul', 'Ago', 'Set', 'Out', 'Nov', 'Dec'],
        days_abbr: ['L-Luns', 'M-Martes', 'X-Mércores', 'X-Xoves', 'V-Venres', 'S-Sábado', 'D-Domingo'],
        quarters: ['1º Trim', '2º Trim', '3º Trim', '4º Trim']
    }
};