const translations = {
    es: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SIN ARCHIVO",
        kpi_reg: "REG",
        lbl_year: "AÑO",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Carga de Datos",
        upload_desc: "Sube tu archivo Excel (.xlsx) o CSV.",
        upload_drop: "ARRASTRAR O TOCAR PARA SUBIR",
        upload_mobile: "Compatible con móviles",
        btn_manual: "Ver Manual",
        btn_updates: "Actualizaciones",
        btn_memorias: "Memorias",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓN",
        config_desc: "Vincula las columnas de tu archivo.",
        col_id: "CONTADOR / ID",
        col_lat: "LATITUD (Y)",
        col_lon: "LONGITUD (X)",
        col_date: "FECHA (Obligatorio)",
        col_time: "HORA (Opcional)",
        col_cat: "CATEGORÍA / TIPO",
        col_cat_desc: "Selecciona la columna que define el tipo de incidencia.",
        col_loc: "LOCALIDAD (Opcional)",
        col_loc_desc: "Escribe el nombre para forzar la zona. Déjalo vacío para GPS.",
        col_loc_placeholder: "Ej: DURANGO",
        btn_cancel: "Cancelar",
        btn_generate: "GENERAR DASHBOARD",
        sidebar_filters: "Filtros",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTROS AVANZADOS",
        filter_years: "Años",
        filter_months: "Meses",
        filter_cats: "Categorías",
        sel_all: "Todos",
        sel_none: "Ninguno",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Expedientes",
        kpi_zona: "Zona",
        kpi_titulo: "TÍTULO",
        kpi_periodo: "Periodo",
        kpi_waiting: "Esperando...",
        kpi_filtered: "Filtrado",
        chart_timeline: "Evolución Temporal",
        chart_top: "Top Tipos",
        chart_hours: "Horas",
        chart_map: "Mapa",
        view_years: "Vista: Años",
        view_months: "Vista: Meses",
        view_quarters: "Vista: Trimestral",
        view_days: "Vista: Días Semanal",
        loading_msg: "Procesando archivo...",
        // Textos de Gráficos
        months_abbr: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        days_abbr: ['L-Lun', 'M-Mar', 'X-Mié', 'J-Jue', 'V-Vie', 'S-Sáb', 'D-Dom'],
        quarters: ['1º Trim', '2º Trim', '3º Trim', '4º Trim'],
        map_layers_title: "Mis Capas",
        map_filter_zone: "Filtrar datos por zona",
        map_no_layers: "Sin capas cargadas",
        btn_add_layer_title: "Subir GeoJSON",
        // PDF Sintesis
        info_tag: "EUROCOP ANALYTICS • SÍNTESIS",
        info_subtitle: "Análisis de datos filtrados",
        info_card_sintesis: "SÍNTESIS PRINCIPAL",
        info_lbl_total: "TOTAL REGISTROS",
        info_lbl_peak: "PICO DE ACTIVIDAD",
        info_lbl_day: "DÍA MÁS ACTIVO",
        info_lbl_trend: "Tendencia Temporal",
        info_lbl_top3: "Top 3 Categorías",
        info_lbl_dominance: "Dominancia",
        info_lbl_footer: "Generado por Eurocop Analytics AI",
        info_insight_text: "La categoría {cat} lidera las incidencias, representando el {percent}% del total.",
        info_trend_morning: "La actividad se concentra principalmente durante la mañana, sugiriendo patrones relacionados con la actividad laboral o comercial.",
        info_trend_afternoon: "Se observa un repunte significativo durante la tarde-noche, típico de actividades sociales y cierre de comercios.",
        info_trend_night: "La actividad nocturna es predominante, lo que podría requerir vigilancia especial en horarios de madrugada.",
        days_full: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        info_report_title: "Informe",
        btn_ai_infographic: "SÍNTESIS"
    },
    eu: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALITIKA",
        no_file: "FITXATEGIRIK EZ",
        kpi_reg: "ERREG",
        lbl_year: "URTEA",
        lbl_month: "HILA",
        lbl_cat: "KAT",
        upload_title: "Datuen Karga",
        upload_desc: "Igo zure Excel (.xlsx) edo CSV fitxategia.",
        upload_drop: "ARRASTRATU EDO UKITU IGOTZEKO",
        upload_mobile: "Mugikorrekin bateragarria",
        btn_manual: "Eskuliburua",
        btn_updates: "Eguneraketak",
        btn_memorias: "Memoriak",
        brand_powered: "Powered by",
        config_title: "KONFIGURAZIOA",
        config_desc: "Lotu zure fitxategiko zutabeak.",
        col_id: "KONTAGAILUA / ID",
        col_lat: "LATITUDEA (Y)",
        col_lon: "LONGITUDEA (X)",
        col_date: "DATA (Nahitaezkoa)",
        col_time: "ORDUA (Aukerakoa)",
        col_cat: "KATEGORIA / MOTA",
        col_cat_desc: "Hautatu intzidentzia mota definitzen duen zutabea.",
        col_loc: "HERRIA (Aukerakoa)",
        col_loc_desc: "Idatzi izena eremua behartzeko. Utzi hutsik GPSrako.",
        col_loc_placeholder: "Adib: DURANGO",
        btn_cancel: "Utzi",
        btn_generate: "DASHBOARDA SORTU",
        sidebar_filters: "Iragazkiak",
        btn_export: "PDF-RA ESPORTATU",
        filter_header: "IRAGAZKI AURRERATUAK",
        filter_years: "Urteak",
        filter_months: "Hilabeteak",
        filter_cats: "Kategoriak",
        sel_all: "Denak",
        sel_none: "Bat ere ez",
        sel_select: "Hautatu...",
        kpi_expedientes: "Espedienteak",
        kpi_zona: "Eremua",
        kpi_titulo: "IZENBURUA",
        kpi_periodo: "Epea",
        kpi_waiting: "Zain...",
        kpi_filtered: "Iragazita",
        chart_timeline: "Denbora Bilakaera",
        chart_top: "Mota Nagusiak",
        chart_hours: "Orduak",
        chart_map: "Mapa",
        view_years: "Ikuspegia: Urteak",
        view_months: "Ikuspegia: Hilabeteak",
        view_quarters: "Ikuspegia: Hiruhilekoa",
        view_days: "Ikuspegia: Asteko Egunak",
        loading_msg: "Fitxategia prozesatzen...",
        months_abbr: ['Urt', 'Ots', 'Mar', 'Api', 'Mai', 'Eka', 'Uzt', 'Abu', 'Ira', 'Urr', 'Aza', 'Abe'],
        days_abbr: ['Al-Astelehena', 'Ar-Asteartea', 'Az-Asteazkena', 'Og-Osteguna', 'Ol-Ostirala', 'Lr-Larunbata', 'Ig-Igandea'],
        quarters: ['1. Hiruh', '2. Hiruh', '3. Hiruh', '4. Hiruh'],
        map_layers_title: "Nire Geruzak",
        map_filter_zone: "Datuak eremuka iragazi",
        map_no_layers: "Kargatutako geruzarik ez",
        btn_add_layer_title: "Igo GeoJSON",
        // PDF Sintesis
        info_tag: "EUROCOP ANALYTICS • SINTESIA",
        info_subtitle: "Filtratutako datuen analisia",
        info_card_sintesis: "SINTESI NAGUSIA",
        info_lbl_total: "ERREGISTROAK GUZTIRA",
        info_lbl_peak: "JARDUERA GORENA",
        info_lbl_day: "EGUN AKTIBOENA",
        info_lbl_trend: "Denbora-joera",
        info_lbl_top3: "3 Kategoria Nagusiak",
        info_lbl_dominance: "Dominantzia",
        info_lbl_footer: "Eurocop Analytics AI-k sortua",
        info_insight_text: "{cat} kategoria da nagusi, gertakarien %{percent} delarik.",
        info_trend_morning: "Jarduerea goizean kontzentratzen da nagusiki, lan- edo merkataritza-jarduerekin lotutako ereduen ondorioz.",
        info_trend_afternoon: "Arratsalde-gauean gorakada nabarmena ikusten da, gizarte-jarduerekin eta denden itxierarekin lotua.",
        info_trend_night: "Gaueko jarduera nagusia da, eta horrek zainketa berezia behar dezake goizaldean.",
        days_full: ['Igandea', 'Astelehena', 'Asteartea', 'Asteazkena', 'Osteguna', 'Ostirala', 'Larunbata'],
        info_report_title: "Txostena",
        btn_ai_infographic: "SINTESIA"
    },
    ca: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SENSE ARXIU",
        kpi_reg: "REG",
        lbl_year: "ANY",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Càrrega de Dades",
        upload_desc: "Puja el teu arxiu Excel (.xlsx) o CSV.",
        upload_drop: "ARROSSEGAR O TOCAR PER PUJAR",
        upload_mobile: "Compatible amb mòbils",
        btn_manual: "Veure Manual",
        btn_updates: "Actualitzacions",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓ",
        config_desc: "Vincula les columnes del teu arxiu.",
        col_id: "COMPTADOR / ID",
        col_lat: "LATITUD (Y)",
        col_lon: "LONGITUD (X)",
        col_date: "DATA (Obligatori)",
        col_time: "HORA (Opcional)",
        col_cat: "CATEGORIA / TIPUS",
        col_cat_desc: "Selecciona la columna que defineix el tipus d'incidència.",
        col_loc: "LOCALITAT (Opcional)",
        col_loc_desc: "Escriu el nom per forçar la zona. Deixa-ho buit per GPS.",
        col_loc_placeholder: "Ex: DURANGO",
        btn_cancel: "Cancel·lar",
        btn_generate: "GENERAR DASHBOARD",
        sidebar_filters: "Filtres",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTRES AVANÇATS",
        filter_years: "Anys",
        filter_months: "Mesos",
        filter_cats: "Categories",
        sel_all: "Tots",
        sel_none: "Cap",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Expedients",
        kpi_zona: "Zona",
        kpi_titulo: "TÍTOL",
        kpi_periodo: "Període",
        kpi_waiting: "Esperant...",
        kpi_filtered: "Filtrat",
        chart_timeline: "Evolució Temporal",
        chart_top: "Top Tipus",
        chart_hours: "Hores",
        chart_map: "Mapa",
        view_years: "Vista: Anys",
        view_months: "Vista: Mesos",
        view_quarters: "Vista: Trimestral",
        view_days: "Vista: Dies Setmanal",
        loading_msg: "Processant l'arxiu...",
        months_abbr: ['Gen', 'Feb', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Des'],
        days_abbr: ['Dl-Dilluns', 'Dm-Dimarts', 'Dc-Dimecres', 'Dj-Dijous', 'Dv-Divendres', 'Ds-Dissabte', 'Dg-Diumenge'],
        quarters: ['1r Trim', '2n Trim', '3r Trim', '4t Trim'],
        map_layers_title: "Les Meves Capes",
        map_filter_zone: "Filtrar dades per zona",
        map_no_layers: "Sense capes carregades",
        btn_add_layer_title: "Pujar GeoJSON",
        // PDF Sintesis
        info_tag: "EUROCOP ANALYTICS • SÍNTESI",
        info_subtitle: "Anàlisi de dades filtrades",
        info_card_sintesis: "SÍNTESI PRINCIPAL",
        info_lbl_total: "TOTAL REGISTRES",
        info_lbl_peak: "PICS D'ACTIVITAT",
        info_lbl_day: "DIA MÉS ACTIU",
        info_lbl_trend: "Tendència Temporal",
        info_lbl_top3: "Top 3 Categories",
        info_lbl_dominance: "Dominància",
        info_lbl_footer: "Generat per Eurocop Analytics AI",
        info_insight_text: "La categoria {cat} lidera les incidències, representant el {percent}% del total.",
        info_trend_morning: "L'activitat es concentra principalment durant el matí, suggerint patrons relacionats amb l'activitat laboral o comercial.",
        info_trend_afternoon: "S'observa un repunt significatiu durant la tarda-nit, típic d'activitats socials i tancament de comerços.",
        info_trend_night: "L'activitat nocturna és predominant, la qual cosa podria requerir vigilància especial en horaris de matinada.",
        days_full: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],
        info_report_title: "Informe",
        btn_ai_infographic: "SÍNTESI"
    },
    gl: {
        nav_title: "EUROCOP",
        nav_analytics: " ANALYTICS",
        no_file: "SEN ARQUIVO",
        kpi_reg: "REX",
        lbl_year: "ANO",
        lbl_month: "MES",
        lbl_cat: "CAT",
        upload_title: "Carga de Datos",
        upload_desc: "Sube o teu arquivo Excel (.xlsx) o CSV.",
        upload_drop: "ARRASTRAR OU TOCAR PARA SUBIR",
        upload_mobile: "Compatible con móbiles",
        btn_manual: "Ver Manual",
        btn_updates: "Actualizacións",
        brand_powered: "Powered by",
        config_title: "CONFIGURACIÓN",
        config_desc: "Vincula as columnas do teu arquivo.",
        col_id: "CONTADOR / ID",
        col_lat: "LATITUDE (Y)",
        col_lon: "LONXITUDE (X)",
        col_date: "DATA (Obrigatorio)",
        col_time: "HORA (Opcional)",
        col_cat: "CATEGORÍA / TIPO",
        col_cat_desc: "Selecciona a columna que define o tipo de incidencia.",
        col_loc: "LOCALIDADE (Opcional)",
        col_loc_desc: "Escribe o nome para forzar a zona. Deixao baleiro para GPS.",
        col_loc_placeholder: "Ex: DURANGO",
        btn_cancel: "Cancelar",
        btn_generate: "XERAR DASHBOARD",
        sidebar_filters: "Filtros",
        btn_export: "EXPORTAR A PDF",
        filter_header: "FILTROS AVANZADOS",
        filter_years: "Anos",
        filter_months: "Meses",
        filter_cats: "Categorías",
        sel_all: "Todos",
        sel_none: "Ningún",
        sel_select: "Seleccionar...",
        kpi_expedientes: "Expedientes",
        kpi_zona: "Zona",
        kpi_titulo: "TÍTULO",
        kpi_periodo: "Período",
        kpi_waiting: "Agardando...",
        kpi_filtered: "Filtrado",
        chart_timeline: "Evolución Temporal",
        chart_top: "Top Tipos",
        chart_hours: "Horas",
        chart_map: "Mapa",
        view_years: "Vista: Anos",
        view_months: "Vista: Meses",
        view_quarters: "Vista: Trimestral",
        view_days: "Vista: Días Semanal",
        loading_msg: "Procesando arquivo...",
        months_abbr: ['Xan', 'Feb', 'Mar', 'Abr', 'Mai', 'Xuñ', 'Xul', 'Ago', 'Set', 'Out', 'Nov', 'Dec'],
        days_abbr: ['L-Luns', 'M-Martes', 'X-Mércores', 'X-Xoves', 'V-Venres', 'S-Sábado', 'D-Domingo'],
        quarters: ['1º Trim', '2º Trim', '3º Trim', '4º Trim'],
        map_layers_title: "As Miñas Capas",
        map_filter_zone: "Filtrar datos por zona",
        map_no_layers: "Sen capas cargadas",
        btn_add_layer_title: "Subir GeoJSON",
        // PDF Sintesis
        info_tag: "EUROCOP ANALYTICS • SÍNTESE",
        info_subtitle: "Análise de datos filtrados",
        info_card_sintesis: "SÍNTESE PRINCIPAL",
        info_lbl_total: "TOTAL REXISTROS",
        info_lbl_peak: "PICO DE ACTIVIDADE",
        info_lbl_day: "DÍA MÁIS ACTIVO",
        info_lbl_trend: "Tendencia Temporal",
        info_lbl_top3: "Top 3 Categorías",
        info_lbl_dominance: "Dominancia",
        info_lbl_footer: "Xerado por Eurocop Analytics AI",
        info_insight_text: "A categoría {cat} lidera as incidencias, representando o {percent}% do total.",
        info_trend_morning: "A actividade concéntrase principalmente durante a mañá, suxerindo patróns relacionados coa actividade laboral ou comercial.",
        info_trend_afternoon: "Obsérvase un repunte significativo durante a tarde-noite, típico de actividades sociais e peche de comercios.",
        info_trend_night: "A actividade nocturna é predominante, o que podería requirir vixilancia especial en horarios de madrugada.",
        days_full: ['Domingo', 'Luns', 'Martes', 'Mércores', 'Xoves', 'Venres', 'Sábado'],
        info_report_title: "Informe",
        btn_ai_infographic: "SÍNTESE"
    }
};